kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kube-ebs-tagger.fullname" . }}
  labels:
{{ include "kube-ebs-tagger.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-ebs-tagger.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "kube-ebs-tagger.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
