kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-ebs-tagger
subjects:
- kind: ServiceAccount
  name: kube-ebs-tagger
roleRef:
  kind: Role
  name: kube-ebs-tagger
  apiGroup: rbac.authorization.k8s.io
